{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fid.fullname" . -}}

{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) -}}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.ext.spec.ingressClassName }}
  {{- end }}
{{- end }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ext
  labels:
    {{- include "fid.labels" . | nindent 4 }}
  {{- with .Values.ingress.ext.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{/*- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) */}}
  ingressClassName: {{ .Values.ingress.ext.spec.ingressClassName }}
  {{/*- end */}}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.ext.spec.rules}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{/*- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion -*/}}
           {{/*- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" */}}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-ext
            port:
              number: 7171
            {{- else}}
        backend:
          serviceName: {{ $fullName }}-ext
          servicePort: 7171
            {{- end  }}
          {{- end }}
    {{- end }}
{{- end }} 